name: Build and Release

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            build_cmd: npm run build:linux
          - os: windows-latest
            platform: windows
            build_cmd: npm run build:win
          - os: macos-latest
            platform: macos
            build_cmd: npm run build:mac

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application (no publish)
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      run: ${{ matrix.build_cmd }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

    - name: Build and publish (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      run: ${{ matrix.build_cmd }} --publish=always
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

